import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex justify-around h-10 bg-slate-300 items-center w-full">
          <div className="flex items-center">
            <Link href="/">
              <Image
                src="/logo.png"
                width={30}
                height={30}
                alt="Logo"
                className="inline mx-5"
              />
            </Link>

            <Link href="/articles" className="mx-5">
              Recent articles
            </Link>

            <Link href="/about" className="mx-5">
              About
            </Link>
          </div>

          <Link href="/login" className="mx-5 text-blue-500">
            Log in
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              className="w-6 h-6 inline mx-1"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3"
              />
            </svg>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
